CMake: Bump minimum required
modelon-community/fmi-library pull request #115
Opened 2024-02-26 15:03 UTC by jschueller

2024-07-01 12:32 UTC, filip-stenstrom requested changes
Would be happy to update this, but there are issues with MSVC. I'm getting these errors:

```
  LINK : the 32-bit linker (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\link.exe) failed to do memory mapped file I/O on `$<TARGET_FILE:libfile_Release>' and is going to restart linking with a 64-bit linker for better throughput

  LINK : failed to locate a 64-bit linker on %PATH%; continue the current linking

LINK : fatal error LNK1104: cannot open file '$<TARGET_FILE:libfile_Release>' [C:\<...>\build_msvc_md\fmilib.vcxproj]
```

MinGW and Ubuntu (GCC) seem to work.

2024-07-01 13:45 UTC, jschueller commented
@filip-stenstrom it should be ok now: I added a msvc CI job

2024-07-02 08:53 UTC, filip-stenstrom commented
> @filip-stenstrom it should be ok now: I added a msvc CI job

Great. Our internal CI is failing though, but on the component testing, i.e. `make test_installation`. It's run after the unit testing. Below is what I'm seeing in the logs.

- The `FMIL_HOME` is using the installation built from the Makefile `install` target.
- The output shows that msvc_md_debug fails, but it's the same for msvc_md and msvc_mt.

```
$ make test CONFIG_FILE=build/config/msvc_md_debug

<build installation>
<unit tests etc...>

set -eu; \
	cd Test/test_installation; \
	rm -rf build && mkdir -p build; \
	cd build; \
	cmake -DFMIL_HOME=/r/.../fmi-library/install_msvc_md_debug -G "Visual Studio 15 2017 Win64" ..; \
	cmake --build .; \
	ctest 
-- The C compiler identification is MSVC 19.14.26429.4
-- The CXX compiler identification is MSVC 19.14.26429.4
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- FMIL_HOME: R:/.../fmi-library/install_msvc_md_debug
-- Configuring done
-- Generating done
-- Build files have been written to: R:/.../fmi-library/Test/test_installation/build
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule R:/.../fmi-library/Test/test_installation/CMakeLists.txt
  main.c
main.obj : error LNK2019: unresolved external symbol jm_get_default_callbacks referenced in function main [R:\...\fmi-library\Test\test_installation\build\main.vcxproj]
main.obj : error LNK2019: unresolved external symbol fmi_import_allocate_context referenced in function main [R:\...\fmi-library\Test\test_installation\build\main.vcxproj]
main.obj : error LNK2019: unresolved external symbol fmi_import_free_context referenced in function main [R:\...\fmi-library\Test\test_installation\build\main.vcxproj]
R:\...\fmi-library\Test\test_installation\build\Debug\main.exe : fatal error LNK1120: 3 unresolved externals [R:\...\fmi-library\Test\test_installation\build\main.vcxproj]
  Building Custom Rule R:/.../fmi-library/Test/test_installation/CMakeLists.txt
  main.c
  main_shared.vcxproj -> R:\...\fmi-library\Test\test_installation\build\Debug\main_shared.exe
make: *** [test_installation] Error 1
```

2025-05-01 14:31 UTC, jschueller commented
hello @filip-stenstrom,

I enabled the installation test on the CI, so now it should hopefully work on your side too.

2025-05-05 14:36 UTC, filip-stenstrom reviewed
Good that you could remove a lot of that multiconfig code. Looking forward to get this merged. Just had one minor comment.

Our internal testing passes, and there we test e.g. MSVC Release and Debug builds, so this should be OK.

2025-05-05 14:56 UTC, jschueller commented on .github/workflows/build.yml
> +          cmake -DCMAKE_INSTALL_PREFIX=C:/Users/runneradmin/fmilib -DFMILIB_GENERATE_DOXYGEN_DOC=0 -B build_ninja -G Ninja -LAH . &&
Its allowed there, cmake wants forward slashes when passing path variables, it will convert to native paths when needed

2025-05-06 06:46 UTC, bilderbuchi commented on .github/workflows/build.yml
> +          cmake -DCMAKE_INSTALL_PREFIX=C:/Users/runneradmin/fmilib -DFMILIB_GENERATE_DOXYGEN_DOC=0 -B build_ninja -G Ninja -LAH . &&
It seems like `cmake_path(SET ..` should convert that as required: https://cmake.org/cmake/help/v3.20/command/cmake_path.html#cmake-path-set
https://stackoverflow.com/a/66304591/599884

2025-05-06 06:54 UTC, jschueller commented on .github/workflows/build.yml
> +          cmake -DCMAKE_INSTALL_PREFIX=C:/Users/runneradmin/fmilib -DFMILIB_GENERATE_DOXYGEN_DOC=0 -B build_ninja -G Ninja -LAH . &&
thats overkill, it would be simpler to replace the slashes in the variable, eg with cmd.exe you could do `%HOME:\=/%`, but I dont know if its that easy in powershell

2025-05-06 07:19 UTC, jschueller commented on .github/workflows/build.yml
> +          cmake -DCMAKE_INSTALL_PREFIX=C:/Users/runneradmin/fmilib -DFMILIB_GENERATE_DOXYGEN_DOC=0 -B build_ninja -G Ninja -LAH . &&
done @filip-stenstrom

2025-05-06 14:04 UTC, filip-stenstrom commented on .github/workflows/build.yml
> +          cmake -DCMAKE_INSTALL_PREFIX=C:/Users/runneradmin/fmilib -DFMILIB_GENERATE_DOXYGEN_DOC=0 -B build_ninja -G Ninja -LAH . &&
Let's go with how it is right now

2025-05-06 14:04 UTC, filip-stenstrom approved these changes

2025-05-06 14:05 UTC, merged