Make list API consistent
modelon-community/fmi-library pull request #69
Opened 2023-06-29 21:58 UTC by MikaelJohnssonModelon

Rename a number of list API methods to be more consistent. 
Prefer _list_t and _list_size as the standard over other alternatives.

2023-07-06 12:20 UTC, PeterMeisrimelModelon requested changes
I only reviewed the API consistency changes for now and not the include changes, the proposed changes look quite involved and I think we are currently lacking proper testing to diagnose any issues there in the first place.

Looks good overall. Left a bunch of comments, since a few cases were missed.

Along with unifying the return type of _get_list_size functions (I'd propose size_t over unsigned int), I think we should also unify the corresponding _get_ functions that take a list + index to then also use size_t as the index type.

Also, when rebasing to master, there will likely be a whole lot of conflict or changes that need to be migrated, since fmi3_import_arrays_test.c was converted to .cpp.

2023-07-06 12:20 UTC, PeterMeisrimelModelon commented on src/Import/src/FMI3/fmi3_import_variable.c
> +size_t fmi3_import_get_alias_variables_number(fmi3_import_alias_variable_list_t* aliases) {
Rename function to `fmi3_import_get_alias_list_size` ?

2023-07-06 12:20 UTC, PeterMeisrimelModelon commented on src/XML/include/FMI3/fmi3_xml_type.h
> +unsigned int fmi3_xml_get_type_definition_number(fmi3_xml_type_definition_list_t* td);
`size_t fmi3_xml_get_type_definition_list_size` ?

2023-07-06 12:20 UTC, PeterMeisrimelModelon commented on src/XML/include/FMI3/fmi3_xml_type.h
> -const char* fmi3_xml_get_enum_type_item_name(fmi3_xml_enumeration_typedef_t*, unsigned int  item);
See comments in corresponding .c file

2023-07-06 12:20 UTC, PeterMeisrimelModelon commented on src/XML/include/FMI3/fmi3_xml_variable.h
> -fmi3_xml_alias_variables_t* fmi3_xml_get_variable_aliases(fmi3_xml_variable_t* v);
See comments in corresponding .c file

2023-07-06 12:20 UTC, PeterMeisrimelModelon commented on src/Import/include/FMI3/fmi3_import_dimension_list.h
> +/** \brief Get a list of dimensions from the import variables */
```suggestion
/** \brief Get a list of dimensions for an import variable */
```

2023-07-06 12:20 UTC, PeterMeisrimelModelon commented on src/Import/include/FMI3/fmi3_import_type.h
> +FMILIB_EXPORT unsigned int fmi3_import_get_type_definition_list_size(fmi3_import_type_definitions_t* td);
unsigned int -> size_t?

2023-07-07 09:25 UTC, MikaelJohnssonModelon commented on src/Import/include/FMI3/fmi3_import_type.h
> -typedef struct fmi3_xml_type_definitions_t fmi3_import_type_definitions_t;
Yes, also found a few others I missed.

2023-07-07 09:42 UTC, MikaelJohnssonModelon commented on src/Import/src/FMI3/fmi3_import.c
> -fmi3_import_unit_definitions_t* fmi3_import_get_unit_definitions(fmi3_import_t* fmu) {
Fixed

2023-07-07 14:32 UTC, MikaelJohnssonModelon commented on src/Import/src/FMI3/fmi3_import.c
> -unsigned int  fmi3_import_get_unit_definitions_number(fmi3_import_unit_definitions_t* ud) {
Yes, fixed.

2023-07-07 14:33 UTC, MikaelJohnssonModelon commented on src/Import/src/FMI3/fmi3_import_type.c
> -unsigned int fmi3_import_get_type_definition_number(fmi3_import_type_definitions_t* td) {
Yes and corrected the name of the method too. To a "_list_size" method.

2023-07-07 14:37 UTC, MikaelJohnssonModelon commented on src/Import/src/FMI3/fmi3_import_type.c
> -const char* fmi3_import_get_enum_type_item_name(fmi3_import_enumeration_typedef_t* t, unsigned int  item) {
Ok, I though this was some enum types and enum literal kinda situation in which case enum_type and enum_type_item sounds kinda clunky.

2023-07-12 07:47 UTC, filip-stenstrom commented on Test/FMI3/fmi3_import_arrays_test.c
> +    dimList = fmi3_import_get_variable_dimension_list(v); /* allocates memory */
No they are now wrong, feel free to fix

2023-07-12 07:49 UTC, filip-stenstrom commented on src/Import/src/FMI3/fmi3_import_type.h
> +/*
Yes I have no idea how that happened. Should be no changes made to it. Just remove

2023-07-12 08:30 UTC, PeterMeisrimelModelon approved these changes

2023-07-12 09:17 UTC, merged